---
- hosts: localhost
  sudo: yes

  tasks:
    - name: install libselinux-python
      yum: name=libselinux-python state=present

    - name: install redis
      yum: name=redis state=latest enablerepo=epel

    - name: install node
      yum: name=nodejs state=latest enablerepo=epel

    - name: install libicu-devel
      yum: name=libicu-devel state=latest

    - name: install nodejs-node-expat for hipchat adapter
      yum: name=nodejs-node-expat state=latest

    - name: install npm
      yum: name=npm state=latest enablerepo=epel

    - name: install coffee-script
      npm: name=coffee-script state=latest global=yes

    - name: install hubot generator
      npm: name={{item}} state=latest global=yes
      with_items:
        - yo
        - generator-hubot

  handlers:

